language: cpp

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - openmpi-bin
      - libopenmpi-dev
      - g++-6
      - libboost1.55-all-dev
      
script:
  - ./configure
  - OMPI_CXX=g++-6 mpiCC -v
  - OMPI_CXX=g++-6 make
  
